export enum BackendEndpoints {
    MAIN_TRAILER = 'static/films/main-trailer.mp4',
    MAIN_PREVIEW = 'static/films/main-preview.jpg',
    MAIN_FILM = 'films/get-main',
    RELEVANT_FILMS = 'films/relevant',
    SUBSCRIBE = 'subscribe',
    SCHEDULE = 'schedule',
    BOOKINGS = 'bookings',
    SEATS = 'seats',
    UPDATE_PROFILE = 'users/update-profile',
    MY_UPCOMING_BOOKINGS = 'bookings/my-upcoming-bookings',
    MY_VISITED_BOOKINGS = 'bookings/my-visited-bookings',
    MY_MISSING_BOOKINGS = 'bookings/my-missing-bookings',
    LOGIN = 'auth/login',
    LOGIN_GOOGLE = 'auth/google',
    LOGIN_FACEBOOK = 'auth/facebook',
    LOGIN_GITHUB = 'auth/github',
    CANCEL_BOOKINGS = 'bookings/cancel',
    REGISTER = 'auth/register',
    REFRESH = 'auth/refresh',
    LOGOUT = 'auth/logout',
    VERIFY = 'auth/verify',
    FILMS = 'films',
}
