export enum EnvFields {
    API_HOST = 'API_HOST',
    API_PORT = 'API_PORT',
    TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
    TYPEORM_USERNAME = 'TYPEORM_USERNAME',
    TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
    TYPEORM_DATABASE = 'TYPEORM_DATABASE',
    TYPEORM_HOST = 'TYPEORM_HOST',
    TYPEORM_PORT = 'TYPEORM_PORT',
}
