export enum EnvFields {
    API_HOST = 'API_HOST',
    API_PORT = 'API_PORT',

    TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
    TYPEORM_USERNAME = 'TYPEORM_USERNAME',
    TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
    TYPEORM_DATABASE = 'TYPEORM_DATABASE',
    TYPEORM_HOST = 'TYPEORM_HOST',
    TYPEORM_PORT = 'TYPEORM_PORT',

    SECRET = 'SECRET',
    EXPIRE_ACCESS_JWT = 'EXPIRE_ACCESS_JWT',
    EXPIRE_REFRESH_JWT = 'EXPIRE_REFRESH_JWT',

    GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
    GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
}
