export enum EnvFields {
    API_HOST = 'API_HOST',
    API_PORT = 'API_PORT',

    TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
    TYPEORM_USERNAME = 'TYPEORM_USERNAME',
    TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
    TYPEORM_DATABASE = 'TYPEORM_DATABASE',
    TYPEORM_HOST = 'TYPEORM_HOST',
    TYPEORM_PORT = 'TYPEORM_PORT',

    SECRET = 'SECRET',
    EXPIRE_ACCESS_JWT = 'EXPIRE_ACCESS_JWT',
    EXPIRE_REFRESH_JWT = 'EXPIRE_REFRESH_JWT',

    GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
    GOOGLE_SECRET = 'GOOGLE_SECRET',
    GOOGLE_CALLBACK = 'GOOGLE_CALLBACK',

    GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
    GITHUB_SECRET = 'GITHUB_SECRET',
    GITHUB_CALLBACK = 'GITHUB_CALLBACK',

    FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
    FACEBOOK_SECRET = 'FACEBOOK_SECRET',
    FACEBOOK_CALLBACK = 'FACEBOOK_CALLBACK',

    MAIL_HOST = 'MAIL_HOST',
    MAIL_USER = 'MAIL_USER',
    MAIL_PASSWORD = 'MAIL_PASSWORD',
    MAIL_FROM = 'MAIL_FROM',
}
