name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: | 
         cd ./backend
         npm install bcrypt
         yarn
         cd ./../frontend
         yarn
         cd ..
      - name: Lint
        run: yarn --cwd ./frontend run lint && yarn --cwd ./backend run lint
